title: Kai Zhang 
logo: "/images/kai_profile.jpeg?raw=true"
description: > 
  Combining creativity with a high dose of enthusiasm, Kai is an initiative taker with
  a permanent thirst for new challenges. He is always looking forward to gain new
  experiences and skills. His social character allows him to work with all kind of people.
  <br><br>
  <br><br>
  kaizhi.zhang92@gmail.com
  <br><br>
  +32 497 77 88 16
  <br><br>
  <a href="https://www.linkedin.com/in/kaizhang92/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 
