title: Kai Zhang 
logo: "/images/kai_profile.webp?raw=true"
description: > 
  Blockchain & Cloud Solutions Architect, 
  with expertise in blockchains, DeFi, Data Analytics,
  Cloud Computing and Machine Learning

  <br><br>
  <br><br>
  <a href="mailto: kaizhi.zhang92@gmail.com">Send me an Email</a>
  <br><br>
  <a href="https://t.me/zkzero">Send me a message on TG</a>
  <br><br>
  <a href="https://www.linkedin.com/in/kaizhizhang/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-WT8LVBXH2Q
